# Generated by Django 4.2.13 on 2024-06-18 04:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_language_value_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='Sort_Summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
