# Generated by Django 4.2.13 on 2024-06-20 04:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_professionalexperience_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='conclusion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='short_summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='technologies_and_tools_used',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='career_objective',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
