# Generated by Django 4.2.13 on 2024-06-20 06:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_projectdetail_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
